CREATE TABLE EMPRESA(
    CODEMPR NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMEEMPR VARCHAR2(50) NOT NULL,
    EMAILEMPR VARCHAR2(50) NOT NULL,
    SENHAEMPR VARCHAR2(8) NOT NULL
);

CREATE TABLE BENEFICIO(
    CODBENE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCBENE VARCHAR2(50) NOT NULL,
    PONTOBENE NUMBER NOT NULL,
    CODEMPR NUMBER NOT NULL,
    CONSTRAINT CODEMPRBENE FOREIGN KEY (CODEMPR) REFERENCES EMPRESA(CODEMPR)
);

CREATE TABLE EMBLEMA(
    CODEMBLE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PONTOEMBLE NUMBER NOT NULL
);

CREATE TABLE ATIVIDADE(
    CODATI NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCATI VARCHAR2(50) NOT NULL,
    PONTOATI NUMBER NOT NULL,
    CODEMPRATI NUMBER NOT NULL,
    CONSTRAINT CODEMPRATI FOREIGN KEY (CODEMPR) REFERENCES EMPRESA(CODEMPR)
);

CREATE TABLE USUARIO(
    CODUSER NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMEUSER VARCHAR2(50) NOT NULL,
    EMAILUSER VARCHAR2(50) NOT NULL,
    SENHAUSER VARCHAR2(8) NOT NULL,
    TIPOUSER VARCHAR2(1) NOT NULL,
    PONTOUSER NUMBER,
    HISTUSER NUMBER,
    CODBENE NUMBER,
    CODEMBLE NUMBER,
    CONSTRAINT BENEUSER FOREIGN KEY (CODBENE) REFERENCES BENEFICIO(CODBENE),
    CONSTRAINT EMBLEUSER FOREIGN KEY (CODEMBLE) REFERENCES EMBLEMA(CODEMBLE)
);