CREATE SCHEMA RECICLA;

USE RECICLA;

CREATE TABLE EMPRESA(
    CODEMPR INT AUTO_INCREMENT PRIMARY KEY,
    NOMEEMPR VARCHAR(50) NOT NULL,
    EMAILEMPR VARCHAR(50) NOT NULL,
    SENHAEMPR VARCHAR(8) NOT NULL
);

CREATE TABLE BENEFICIO(
    CODBENE INT AUTO_INCREMENT PRIMARY KEY,
    DESCBENE VARCHAR(50) NOT NULL,
    PONTOBENE INT NOT NULL,
    CODEMPR INT NOT NULL,
    CONSTRAINT CODEMPRBENE FOREIGN KEY (CODEMPR) REFERENCES EMPRESA(CODEMPR)
);

CREATE TABLE EMBLEMA(
    CODEMBLE INT AUTO_INCREMENT PRIMARY KEY,
    PONTOEMBLE INT NOT NULL
);

CREATE TABLE ATIVIDADE(
    CODATI INT AUTO_INCREMENT PRIMARY KEY,
    DESCATI VARCHAR(50) NOT NULL,
    PONTOATI INT NOT NULL,
    CODEMPRATI INT NOT NULL,
    CODEMPR INT NOT NULL,
    CONSTRAINT CODEMPRATI FOREIGN KEY (CODEMPR) REFERENCES EMPRESA(CODEMPR)
);

CREATE TABLE USUARIO(
    CODUSER INT AUTO_INCREMENT PRIMARY KEY,
    NOMEUSER VARCHAR(50) NOT NULL,
    EMAILUSER VARCHAR(50) NOT NULL UNIQUE,
    SENHAUSER VARCHAR(8) NOT NULL,
    TIPOUSER VARCHAR(1),
    PONTOUSER INT,
    HISTUSER INT,
    CODBENE INT,
    CODEMBLE INT,
    CONSTRAINT BENEUSER FOREIGN KEY (CODBENE) REFERENCES BENEFICIO(CODBENE),
    CONSTRAINT EMBLEUSER FOREIGN KEY (CODEMBLE) REFERENCES EMBLEMA(CODEMBLE)
);

CREATE TABLE Photos(
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(255), 
Data LONGBLOB, 
ContentType VARCHAR(100), 
CreatedAt DATETIME);